In [3]:
import pandas as pd

results = pd.read_csv('../data/results.csv')
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [4]:
print(results.shape)
print(results.columns.tolist())

(26759, 18)
['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid', 'position', 'positionText', 'positionOrder', 'points', 'laps', 'time', 'milliseconds', 'fastestLap', 'rank', 'fastestLapTime', 'fastestLapSpeed', 'statusId']

In [5]:
races = pd.read_csv('../data/races.csv')
drivers = pd.read_csv('../data/drivers.csv')

races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [6]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [7]:
results['top10_finish'] = (results['positionOrder'] <= 10).astype(int)
results[['driverId', 'raceId', 'grid', 'positionOrder', 'top10_finish']].head(10)

   driverId  raceId  grid  positionOrder  top10_finish
0         1      18     1              1             1
1         2      18     5              2             1
2         3      18     7              3             1
3         4      18    11              4             1
4         5      18     3              5             1
5         6      18    13              6             1
6         7      18    17              7             1
7         8      18    15              8             1
8         9      18     2              9             1
9        10      18    18             10             1

In [8]:
results[['driverId', 'raceId', 'grid', 'positionOrder', 'top10_finish']].tail(10)

       driverId  raceId  grid  positionOrder  top10_finish
26749       848    1144    18             11             0
26750       852    1144    11             12             0
26751       855    1144    15             13             0
26752       840    1144    13             14             0
26753       862    1144    17             15             0
26754       825    1144    14             16             0
26755       859    1144    12             17             0
26756       822    1144     9             18             0
26757       861    1144    20             19             0
26758       815    1144    10             20             0

In [9]:
df =  results.merge(races[['raceId', 'year', 'name', 'circuitId']], on='raceId')
df = df.merge(drivers[['driverId', 'forename', 'surname', 'nationality']], on='driverId')

df[['year', 'name', 'forename', 'surname', 'grid', 'positionOrder', 'top10_finish']].head(10)

,year,name,forename,surname,grid,positionOrder,top10_finish
0,2008,Australian Grand Prix,Lewis,Hamilton,1,1,1
1,2008,Australian Grand Prix,Nick,Heidfeld,5,2,1
2,2008,Australian Grand Prix,Nico,Rosberg,7,3,1
3,2008,Australian Grand Prix,Fernando,Alonso,11,4,1
4,2008,Australian Grand Prix,Heikki,Kovalainen,3,5,1
5,2008,Australian Grand Prix,Kazuki,Nakajima,13,6,1
6,2008,Australian Grand Prix,Sébastien,Bourdais,17,7,1
7,2008,Australian Grand Prix,Kimi,Räikkönen,15,8,1
8,2008,Australian Grand Prix,Robert,Kubica,2,9,1
9,2008,Australian Grand Prix,Timo,Glock,18,10,1

In [10]:
df = df.sort_values(['driverId' , 'year' , 'raceId'])
df['avg_last5_finish'] = (
    df.groupby('driverId')['positionOrder']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

df[['forename', 'surname', 'year', 'name', 'positionOrder', 'avg_last5_finish']].head(15)

,forename,surname,year,name,positionOrder,avg_last5_finish
370,Lewis,Hamilton,2007,Australian Grand Prix,3,NaN
391,Lewis,Hamilton,2007,Malaysian Grand Prix,2,3.000000
413,Lewis,Hamilton,2007,Bahrain Grand Prix,2,2.500000
435,Lewis,Hamilton,2007,Spanish Grand Prix,2,2.333333
457,Lewis,Hamilton,2007,Monaco Grand Prix,2,2.250000
478,Lewis,Hamilton,2007,Canadian Grand Prix,1,2.200000
500,Lewis,Hamilton,2007,United States Grand Prix,1,1.800000
524,Lewis,Hamilton,2007,French Grand Prix,3,1.600000
546,Lewis,Hamilton,2007,British Grand Prix,3,1.800000
574,Lewis,Hamilton,2007,European Grand Prix,9,2.000000
588,Lewis,Hamilton,2007,Hungarian Grand Prix,1,3.400000
614,Lewis,Hamilton,2007,Turkish Grand Prix,5,3.400000
633,Lewis,Hamilton,2007,Italian Grand Prix,2,4.200000
657,Lewis,Hamilton,2007,Belgian Grand Prix,4,4.000000
676,Lewis,Hamilton,2007,Japanese Grand Prix,1,4.200000

In [23]:
df['constructor_avg_last5'] = (
    df.groupby('constructorId')['positionOrder']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

df[['forename', 'surname', 'name', 'year', 'positionOrder', 'avg_last5_finish', 'constructor_avg_last5']].head(15)

,forename,surname,name,year,positionOrder,avg_last5_finish,constructor_avg_last5
370,Lewis,Hamilton,Australian Grand Prix,2007,3,NaN,NaN
391,Lewis,Hamilton,Malaysian Grand Prix,2007,2,3.000000,3.000000
413,Lewis,Hamilton,Bahrain Grand Prix,2007,2,2.500000,2.500000
435,Lewis,Hamilton,Spanish Grand Prix,2007,2,2.333333,2.333333
457,Lewis,Hamilton,Monaco Grand Prix,2007,2,2.250000,2.250000
478,Lewis,Hamilton,Canadian Grand Prix,2007,1,2.200000,2.200000
500,Lewis,Hamilton,United States Grand Prix,2007,1,1.800000,1.800000
524,Lewis,Hamilton,French Grand Prix,2007,3,1.600000,1.600000
546,Lewis,Hamilton,British Grand Prix,2007,3,1.800000,1.800000
574,Lewis,Hamilton,European Grand Prix,2007,9,2.000000,2.000000
588,Lewis,Hamilton,Hungarian Grand Prix,2007,1,3.400000,3.400000
614,Lewis,Hamilton,Turkish Grand Prix,2007,5,3.400000,3.400000
633,Lewis,Hamilton,Italian Grand Prix,2007,2,4.200000,4.200000
657,Lewis,Hamilton,Belgian Grand Prix,2007,4,4.000000,4.000000
676,Lewis,Hamilton,Japanese Grand Prix,2007,1,4.200000,4.200000

In [24]:
df['grid_vs_form'] = df['avg_last5_finish'] - df['grid']

In [13]:
df[df['constructorId'] == df.loc[370, 'constructorId']][['forename', 'surname', 'year', 'name', 'positionOrder']].head(20)

    forename   surname  year                      name  positionOrder
370    Lewis  Hamilton  2007     Australian Grand Prix              3
391    Lewis  Hamilton  2007      Malaysian Grand Prix              2
413    Lewis  Hamilton  2007        Bahrain Grand Prix              2
435    Lewis  Hamilton  2007        Spanish Grand Prix              2
457    Lewis  Hamilton  2007         Monaco Grand Prix              2
478    Lewis  Hamilton  2007       Canadian Grand Prix              1
500    Lewis  Hamilton  2007  United States Grand Prix              1
524    Lewis  Hamilton  2007         French Grand Prix              3
546    Lewis  Hamilton  2007        British Grand Prix              3
574    Lewis  Hamilton  2007       European Grand Prix              9
588    Lewis  Hamilton  2007      Hungarian Grand Prix              1
614    Lewis  Hamilton  2007        Turkish Grand Prix              5
633    Lewis  Hamilton  2007        Italian Grand Prix              2
657    Lewis  Hamilton  2007        Belgian Grand Prix              4
676    Lewis  Hamilton  2007       Japanese Grand Prix              1
716    Lewis  Hamilton  2007        Chinese Grand Prix             19
726    Lewis  Hamilton  2007      Brazilian Grand Prix              7
0      Lewis  Hamilton  2008     Australian Grand Prix              1
26     Lewis  Hamilton  2008      Malaysian Grand Prix              5
56     Lewis  Hamilton  2008        Bahrain Grand Prix             13

In [14]:
constructor_sorted = df.sort_values(['constructorId', 'year', 'raceId'])
constructor_sorted['constructor_avg_last5'] = (
    constructor_sorted.groupby('constructorId')['positionOrder']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)
df['constructor_avg_last5'] = constructor_sorted['constructor_avg_last5']

In [15]:
df[(df['constructorId'] == df.loc[370, 'constructorId']) & (df['year'] == 2007)][['forename', 'surname', 'name', 'positionOrder']]

     forename   surname                      name  positionOrder
370     Lewis  Hamilton     Australian Grand Prix              3
391     Lewis  Hamilton      Malaysian Grand Prix              2
413     Lewis  Hamilton        Bahrain Grand Prix              2
435     Lewis  Hamilton        Spanish Grand Prix              2
457     Lewis  Hamilton         Monaco Grand Prix              2
478     Lewis  Hamilton       Canadian Grand Prix              1
500     Lewis  Hamilton  United States Grand Prix              1
524     Lewis  Hamilton         French Grand Prix              3
546     Lewis  Hamilton        British Grand Prix              3
574     Lewis  Hamilton       European Grand Prix              9
588     Lewis  Hamilton      Hungarian Grand Prix              1
614     Lewis  Hamilton        Turkish Grand Prix              5
633     Lewis  Hamilton        Italian Grand Prix              2
657     Lewis  Hamilton        Belgian Grand Prix              4
676     Lewis  Hamilton       Japanese Grand Prix              1
716     Lewis  Hamilton        Chinese Grand Prix             19
726     Lewis  Hamilton      Brazilian Grand Prix              7
369  Fernando    Alonso     Australian Grand Prix              2
390  Fernando    Alonso      Malaysian Grand Prix              1
416  Fernando    Alonso        Bahrain Grand Prix              5
436  Fernando    Alonso        Spanish Grand Prix              3
456  Fernando    Alonso         Monaco Grand Prix              1
484  Fernando    Alonso       Canadian Grand Prix              7
501  Fernando    Alonso  United States Grand Prix              2
528  Fernando    Alonso         French Grand Prix              7
545  Fernando    Alonso        British Grand Prix              2
566  Fernando    Alonso       European Grand Prix              1
591  Fernando    Alonso      Hungarian Grand Prix              4
612  Fernando    Alonso        Turkish Grand Prix              3
632  Fernando    Alonso        Italian Grand Prix              1
656  Fernando    Alonso        Belgian Grand Prix              3
696  Fernando    Alonso       Japanese Grand Prix             21
699  Fernando    Alonso        Chinese Grand Prix              2
722  Fernando    Alonso      Brazilian Grand Prix              3

In [16]:
df[['forename', 'surname', 'name', 'year', 'positionOrder', 'avg_last5_finish', 'constructor_avg_last5']].head(15)

,forename,surname,name,year,positionOrder,avg_last5_finish,constructor_avg_last5
370,Lewis,Hamilton,Australian Grand Prix,2007,3,NaN,6.8
391,Lewis,Hamilton,Malaysian Grand Prix,2007,2,3.000000,5.8
413,Lewis,Hamilton,Bahrain Grand Prix,2007,2,2.500000,3.2
435,Lewis,Hamilton,Spanish Grand Prix,2007,2,2.333333,2.4
457,Lewis,Hamilton,Monaco Grand Prix,2007,2,2.250000,2.6
478,Lewis,Hamilton,Canadian Grand Prix,2007,1,2.200000,2.6
500,Lewis,Hamilton,United States Grand Prix,2007,1,1.800000,2.8
524,Lewis,Hamilton,French Grand Prix,2007,3,1.600000,2.4
546,Lewis,Hamilton,British Grand Prix,2007,3,1.800000,4.0
574,Lewis,Hamilton,European Grand Prix,2007,9,2.000000,3.4
588,Lewis,Hamilton,Hungarian Grand Prix,2007,1,3.400000,4.4
614,Lewis,Hamilton,Turkish Grand Prix,2007,5,3.400000,3.4
633,Lewis,Hamilton,Italian Grand Prix,2007,2,4.200000,2.8
657,Lewis,Hamilton,Belgian Grand Prix,2007,4,4.000000,3.0
676,Lewis,Hamilton,Japanese Grand Prix,2007,1,4.200000,2.6

In [17]:
df_model =  df.dropna(subset= ['avg_last5_finish','constructor_avg_last5','grid_vs_form'])
print(df.shape,'->',df_model.shape)

(26759, 28) -> (25764, 28)

In [18]:
features = ['grid','avg_last5_finish','constructor_avg_last5','grid_vs_form']
train = df_model[df_model['year'] <=2019]
test =  df_model[df_model['year'] >2019]
X_train , y_train = train[features],train['top10_finish']
X_test , y_test = test[features],test['top10_finish']
print(X_train.shape, X_test.shape)

(23642, 4) (2122, 4)

In [21]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression()
model.fit(X_train,y_train)
print("Train accuracy:",model.score(X_train,y_train))
print("Test accuracy:",model.score(X_test,y_test))

Train accuracy: 0.6862363590220794
Test accuracy: 0.7667295004712535

In [22]:
baseline_model = LogisticRegression()
baseline_model.fit(train[['grid']],y_train)
print("Baseline (grid only) test accuracy:",baseline_model.score(test[['grid']],y_test))

Baseline (grid only) test accuracy: 0.6932139491046183

In [26]:
from sklearn.metrics import classification_report , confusion_matrix
y_pred = model.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[816 240]
 [255 811]]
              precision    recall  f1-score   support

           0       0.76      0.77      0.77      1056
           1       0.77      0.76      0.77      1066

    accuracy                           0.77      2122
   macro avg       0.77      0.77      0.77      2122
weighted avg       0.77      0.77      0.77      2122

In [28]:
from sklearn.metrics import roc_auc_score
y_prob = model.predict_proba(X_test)[:,1]
roc_auc = roc_auc_score(y_test,y_prob)
print("ROC-AUC:",roc_auc)

ROC-AUC: 0.839933694354426

In [30]:
import pandas as pd 
coef_df = pd.DataFrame({
    'feature':features,
    'coefficient':model.coef_[0]})
print(coef_df)

                 feature  coefficient
0                   grid    -0.056925
1       avg_last5_finish    -0.071488
2  constructor_avg_last5    -0.084197
3           grid_vs_form    -0.014563

In [32]:
sample = test.copy()
sample['predicted_prob']  = model.predict_proba(X_test)[:,1]
sample['predicted_top10'] = model.predict(X_test)

sample[['forename', 'surname', 'name', 'year', 'positionOrder', 'top10_finish','predicted_prob','predicted_top10']].sort_values('year').head(20)

,forename,surname,name,year,positionOrder,top10_finish,predicted_prob,predicted_top10
24623,Lewis,Hamilton,Austrian Grand Prix,2020,4,1,0.780534,1
24700,Max,Verstappen,70th Anniversary Grand Prix,2020,1,1,0.778175,1
24681,Max,Verstappen,British Grand Prix,2020,2,1,0.770935,1
24661,Max,Verstappen,Hungarian Grand Prix,2020,2,1,0.669737,1
24642,Max,Verstappen,Styrian Grand Prix,2020,3,1,0.671641,1
24639,Max,Verstappen,Austrian Grand Prix,2020,20,0,0.769360,1
24950,Daniil,Kvyat,Abu Dhabi Grand Prix,2020,11,0,0.564703,1
24926,Daniil,Kvyat,Sakhir Grand Prix,2020,7,1,0.482308,0
24910,Daniil,Kvyat,Bahrain Grand Prix,2020,11,0,0.486528,0
24891,Daniil,Kvyat,Turkish Grand Prix,2020,12,0,0.444722,0
24863,Daniil,Kvyat,Emilia Romagna Grand Prix,2020,4,1,0.507705,1
24858,Daniil,Kvyat,Portuguese Grand Prix,2020,19,0,0.472363,0
24834,Daniil,Kvyat,Eifel Grand Prix,2020,15,0,0.539885,1
24807,Daniil,Kvyat,Russian Grand Prix,2020,8,1,0.552353,1
24786,Daniil,Kvyat,Tuscan Grand Prix,2020,7,1,0.524078,1
24768,Daniil,Kvyat,Italian Grand Prix,2020,9,1,0.467099,0
24750,Daniil,Kvyat,Belgian Grand Prix,2020,11,0,0.479784,0
24731,Daniil,Kvyat,Spanish Grand Prix,2020,12,0,0.399023,0
24778,Kevin,Magnussen,Italian Grand Prix,2020,19,0,0.256224,0
24795,Kevin,Magnussen,Tuscan Grand Prix,2020,16,0,0.200709,0

In [33]:
sample[['forename', 'surname', 'name', 'year', 'positionOrder', 'top10_finish','predicted_prob','predicted_top10']].sort_values('predicted_prob',ascending = False).head(20)

,forename,surname,name,year,positionOrder,top10_finish,predicted_prob,predicted_top10
26300,Max,Verstappen,Saudi Arabian Grand Prix,2024,1,1,0.878726,1
26080,Max,Verstappen,Dutch Grand Prix,2023,1,1,0.876920,1
26280,Max,Verstappen,Bahrain Grand Prix,2024,1,1,0.876920,1
26338,Max,Verstappen,Australian Grand Prix,2024,19,0,0.876920,1
24766,Lewis,Hamilton,Italian Grand Prix,2020,7,1,0.876880,1
26100,Max,Verstappen,Italian Grand Prix,2023,1,1,0.874139,1
26260,Max,Verstappen,Abu Dhabi Grand Prix,2023,1,1,0.873239,1
25884,Sergio,Pérez,Australian Grand Prix,2023,5,1,0.868069,1
26000,Max,Verstappen,Austrian Grand Prix,2023,1,1,0.867498,1
24838,Valtteri,Bottas,Eifel Grand Prix,2020,19,0,0.867200,1
26040,Max,Verstappen,Hungarian Grand Prix,2023,1,1,0.866540,1
25541,Sergio,Pérez,Azerbaijan Grand Prix,2022,2,1,0.866282,1
26020,Max,Verstappen,British Grand Prix,2023,1,1,0.865594,1
25780,Max,Verstappen,Mexico City Grand Prix,2022,1,1,0.865335,1
25880,Max,Verstappen,Australian Grand Prix,2023,1,1,0.865335,1
24680,Lewis,Hamilton,British Grand Prix,2020,1,1,0.865205,1
25921,Sergio,Pérez,Miami Grand Prix,2023,2,1,0.863317,1
25901,Max,Verstappen,Azerbaijan Grand Prix,2023,2,1,0.862333,1
26642,Lando,Norris,United States Grand Prix,2024,4,1,0.859204,1
24740,Lewis,Hamilton,Belgian Grand Prix,2020,1,1,0.857517,1

In [38]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(
    n_estimators = 100,
    random_state = 42  
)
rf_model.fit(X_train,y_train)
print('RF Train accuracy:' , rf_model.score(X_train,y_train))
print('RF Test accuracy:' , rf_model.score(X_test,y_test))
rf_proba = rf_model.predict_proba(X_test)[:,1]
print('RF ROC-AUC:',roc_auc_score(y_test,rf_proba))

RF Train accuracy: 0.9623128330936469
RF Test accuracy: 0.6861451460885957
RF ROC-AUC: 0.7463826823582921

In [62]:
qualifying = pd.read_csv('../data/qualifying.csv')
print(qualifying.shape)
print(qualifying.columns.tolist())
qualifying.head()

(10494, 9)
['qualifyId', 'raceId', 'driverId', 'constructorId', 'number', 'position', 'q1', 'q2', 'q3']

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [63]:
def time_to_seconds(time):
    if pd.isna(time):
        return None
    time = str(time).strip()

    if ':' not in time:
        return None

    minutes, seconds = time.split(':', 1)
    return int(minutes) * 60 + float(seconds)

In [64]:
print(time_to_seconds('1:26.572'))

86.572

In [65]:
for col in ['q1','q2','q3']:
    qualifying[col + '_seconds'] = qualifying[col].apply(time_to_seconds)

In [66]:
qualifying[['qualifyId', 'raceId', 'driverId', 'constructorId', 'number', 'position', 'q1', 'q2', 'q3','q1_seconds', 'q2_seconds', 'q3_seconds']].head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3,q1_seconds,q2_seconds,q3_seconds
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714,86.572,85.187,86.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869,86.103,85.315,86.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079,85.664,85.452,87.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178,85.994,85.691,87.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236,85.960,85.518,87.236

In [67]:
qualifying['best_quali_time'] =qualifying[['q1_seconds', 'q2_seconds', 'q3_seconds']].min(axis=1)

In [75]:
pole_times = (
    qualifying.groupby('raceId')['best_quali_time']
    .min()
    .reset_index()
    .rename(columns={'best_quali_time': 'pole_time'})
)

In [76]:
pole_time_map = pole_times.set_index('raceId')['pole_time']

qualifying['pole_time'] = qualifying['raceId'].map(pole_time_map)

In [77]:
qualifying['qualifying_gap'] = (
    qualifying['best_quali_time']
    - qualifying['pole_time']
)

In [78]:
qualifying[
    [
        'raceId',
        'driverId',
        'best_quali_time',
        'pole_time',
        'qualifying_gap'
    ]
].head(10)

   raceId  driverId  best_quali_time  pole_time  qualifying_gap
0      18         1           85.187     85.187           0.000
1      18         9           85.315     85.187           0.128
2      18         5           85.452     85.187           0.265
3      18        13           85.691     85.187           0.504
4      18         2           85.518     85.187           0.331
5      18        15           86.101     85.187           0.914
6      18         3           86.059     85.187           0.872
7      18        14           86.063     85.187           0.876
8      18        10           86.164     85.187           0.977
9      18        20           85.842     85.187           0.655