In [2]:
import pandas as pd

results = pd.read_csv('../data/results.csv')
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [3]:
print(results.shape)
print(results.columns.tolist())

(26759, 18)
['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid', 'position', 'positionText', 'positionOrder', 'points', 'laps', 'time', 'milliseconds', 'fastestLap', 'rank', 'fastestLapTime', 'fastestLapSpeed', 'statusId']

In [4]:
races = pd.read_csv('../data/races.csv')
drivers = pd.read_csv('../data/drivers.csv')

races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [5]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [6]:
results['top10_finish'] = (results['positionOrder'] <= 10).astype(int)
results[['driverId', 'raceId', 'grid', 'positionOrder', 'top10_finish']].head(10)

   driverId  raceId  grid  positionOrder  top10_finish
0         1      18     1              1             1
1         2      18     5              2             1
2         3      18     7              3             1
3         4      18    11              4             1
4         5      18     3              5             1
5         6      18    13              6             1
6         7      18    17              7             1
7         8      18    15              8             1
8         9      18     2              9             1
9        10      18    18             10             1

In [7]:
results[['driverId', 'raceId', 'grid', 'positionOrder', 'top10_finish']].tail(10)

       driverId  raceId  grid  positionOrder  top10_finish
26749       848    1144    18             11             0
26750       852    1144    11             12             0
26751       855    1144    15             13             0
26752       840    1144    13             14             0
26753       862    1144    17             15             0
26754       825    1144    14             16             0
26755       859    1144    12             17             0
26756       822    1144     9             18             0
26757       861    1144    20             19             0
26758       815    1144    10             20             0

In [8]:
df =  results.merge(races[['raceId', 'year', 'name', 'circuitId']], on='raceId')
df = df.merge(drivers[['driverId', 'forename', 'surname', 'nationality']], on='driverId')

df[['year', 'name', 'forename', 'surname', 'grid', 'positionOrder', 'top10_finish']].head(10)

,year,name,forename,surname,grid,positionOrder,top10_finish
0,2008,Australian Grand Prix,Lewis,Hamilton,1,1,1
1,2008,Australian Grand Prix,Nick,Heidfeld,5,2,1
2,2008,Australian Grand Prix,Nico,Rosberg,7,3,1
3,2008,Australian Grand Prix,Fernando,Alonso,11,4,1
4,2008,Australian Grand Prix,Heikki,Kovalainen,3,5,1
5,2008,Australian Grand Prix,Kazuki,Nakajima,13,6,1
6,2008,Australian Grand Prix,Sébastien,Bourdais,17,7,1
7,2008,Australian Grand Prix,Kimi,Räikkönen,15,8,1
8,2008,Australian Grand Prix,Robert,Kubica,2,9,1
9,2008,Australian Grand Prix,Timo,Glock,18,10,1

In [9]:
df = df.sort_values(['driverId' , 'year' , 'raceId'])
df['avg_last5_finish'] = (
    df.groupby('driverId')['positionOrder']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

df[['forename', 'surname', 'year', 'name', 'positionOrder', 'avg_last5_finish']].head(15)

,forename,surname,year,name,positionOrder,avg_last5_finish
370,Lewis,Hamilton,2007,Australian Grand Prix,3,NaN
391,Lewis,Hamilton,2007,Malaysian Grand Prix,2,3.000000
413,Lewis,Hamilton,2007,Bahrain Grand Prix,2,2.500000
435,Lewis,Hamilton,2007,Spanish Grand Prix,2,2.333333
457,Lewis,Hamilton,2007,Monaco Grand Prix,2,2.250000
478,Lewis,Hamilton,2007,Canadian Grand Prix,1,2.200000
500,Lewis,Hamilton,2007,United States Grand Prix,1,1.800000
524,Lewis,Hamilton,2007,French Grand Prix,3,1.600000
546,Lewis,Hamilton,2007,British Grand Prix,3,1.800000
574,Lewis,Hamilton,2007,European Grand Prix,9,2.000000
588,Lewis,Hamilton,2007,Hungarian Grand Prix,1,3.400000
614,Lewis,Hamilton,2007,Turkish Grand Prix,5,3.400000
633,Lewis,Hamilton,2007,Italian Grand Prix,2,4.200000
657,Lewis,Hamilton,2007,Belgian Grand Prix,4,4.000000
676,Lewis,Hamilton,2007,Japanese Grand Prix,1,4.200000

In [10]:
df['constructor_avg_last5'] = (
    df.groupby('constructorId')['positionOrder']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

df[['forename', 'surname', 'name', 'year', 'positionOrder', 'avg_last5_finish', 'constructor_avg_last5']].head(15)

,forename,surname,name,year,positionOrder,avg_last5_finish,constructor_avg_last5
370,Lewis,Hamilton,Australian Grand Prix,2007,3,NaN,NaN
391,Lewis,Hamilton,Malaysian Grand Prix,2007,2,3.000000,3.000000
413,Lewis,Hamilton,Bahrain Grand Prix,2007,2,2.500000,2.500000
435,Lewis,Hamilton,Spanish Grand Prix,2007,2,2.333333,2.333333
457,Lewis,Hamilton,Monaco Grand Prix,2007,2,2.250000,2.250000
478,Lewis,Hamilton,Canadian Grand Prix,2007,1,2.200000,2.200000
500,Lewis,Hamilton,United States Grand Prix,2007,1,1.800000,1.800000
524,Lewis,Hamilton,French Grand Prix,2007,3,1.600000,1.600000
546,Lewis,Hamilton,British Grand Prix,2007,3,1.800000,1.800000
574,Lewis,Hamilton,European Grand Prix,2007,9,2.000000,2.000000
588,Lewis,Hamilton,Hungarian Grand Prix,2007,1,3.400000,3.400000
614,Lewis,Hamilton,Turkish Grand Prix,2007,5,3.400000,3.400000
633,Lewis,Hamilton,Italian Grand Prix,2007,2,4.200000,4.200000
657,Lewis,Hamilton,Belgian Grand Prix,2007,4,4.000000,4.000000
676,Lewis,Hamilton,Japanese Grand Prix,2007,1,4.200000,4.200000

In [14]:
df['grid_vs_form'] = df['avg_last5_finish'] - df['grid']

In [13]:
df[df['constructorId'] == df.loc[370, 'constructorId']][['forename', 'surname', 'year', 'name', 'positionOrder']].head(20)

    forename   surname  year                      name  positionOrder
370    Lewis  Hamilton  2007     Australian Grand Prix              3
391    Lewis  Hamilton  2007      Malaysian Grand Prix              2
413    Lewis  Hamilton  2007        Bahrain Grand Prix              2
435    Lewis  Hamilton  2007        Spanish Grand Prix              2
457    Lewis  Hamilton  2007         Monaco Grand Prix              2
478    Lewis  Hamilton  2007       Canadian Grand Prix              1
500    Lewis  Hamilton  2007  United States Grand Prix              1
524    Lewis  Hamilton  2007         French Grand Prix              3
546    Lewis  Hamilton  2007        British Grand Prix              3
574    Lewis  Hamilton  2007       European Grand Prix              9
588    Lewis  Hamilton  2007      Hungarian Grand Prix              1
614    Lewis  Hamilton  2007        Turkish Grand Prix              5
633    Lewis  Hamilton  2007        Italian Grand Prix              2
657    Lewis  Hamilton  2007        Belgian Grand Prix              4
676    Lewis  Hamilton  2007       Japanese Grand Prix              1
716    Lewis  Hamilton  2007        Chinese Grand Prix             19
726    Lewis  Hamilton  2007      Brazilian Grand Prix              7
0      Lewis  Hamilton  2008     Australian Grand Prix              1
26     Lewis  Hamilton  2008      Malaysian Grand Prix              5
56     Lewis  Hamilton  2008        Bahrain Grand Prix             13

In [15]:
constructor_sorted = df.sort_values(['constructorId', 'year', 'raceId'])
constructor_sorted['constructor_avg_last5'] = (
    constructor_sorted.groupby('constructorId')['positionOrder']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)
df['constructor_avg_last5'] = constructor_sorted['constructor_avg_last5']

In [16]:
df[(df['constructorId'] == df.loc[370, 'constructorId']) & (df['year'] == 2007)][['forename', 'surname', 'name', 'positionOrder']]

     forename   surname                      name  positionOrder
370     Lewis  Hamilton     Australian Grand Prix              3
391     Lewis  Hamilton      Malaysian Grand Prix              2
413     Lewis  Hamilton        Bahrain Grand Prix              2
435     Lewis  Hamilton        Spanish Grand Prix              2
457     Lewis  Hamilton         Monaco Grand Prix              2
478     Lewis  Hamilton       Canadian Grand Prix              1
500     Lewis  Hamilton  United States Grand Prix              1
524     Lewis  Hamilton         French Grand Prix              3
546     Lewis  Hamilton        British Grand Prix              3
574     Lewis  Hamilton       European Grand Prix              9
588     Lewis  Hamilton      Hungarian Grand Prix              1
614     Lewis  Hamilton        Turkish Grand Prix              5
633     Lewis  Hamilton        Italian Grand Prix              2
657     Lewis  Hamilton        Belgian Grand Prix              4
676     Lewis  Hamilton       Japanese Grand Prix              1
716     Lewis  Hamilton        Chinese Grand Prix             19
726     Lewis  Hamilton      Brazilian Grand Prix              7
369  Fernando    Alonso     Australian Grand Prix              2
390  Fernando    Alonso      Malaysian Grand Prix              1
416  Fernando    Alonso        Bahrain Grand Prix              5
436  Fernando    Alonso        Spanish Grand Prix              3
456  Fernando    Alonso         Monaco Grand Prix              1
484  Fernando    Alonso       Canadian Grand Prix              7
501  Fernando    Alonso  United States Grand Prix              2
528  Fernando    Alonso         French Grand Prix              7
545  Fernando    Alonso        British Grand Prix              2
566  Fernando    Alonso       European Grand Prix              1
591  Fernando    Alonso      Hungarian Grand Prix              4
612  Fernando    Alonso        Turkish Grand Prix              3
632  Fernando    Alonso        Italian Grand Prix              1
656  Fernando    Alonso        Belgian Grand Prix              3
696  Fernando    Alonso       Japanese Grand Prix             21
699  Fernando    Alonso        Chinese Grand Prix              2
722  Fernando    Alonso      Brazilian Grand Prix              3

In [17]:
df[['forename', 'surname', 'name', 'year', 'positionOrder', 'avg_last5_finish', 'constructor_avg_last5']].head(15)

,forename,surname,name,year,positionOrder,avg_last5_finish,constructor_avg_last5
370,Lewis,Hamilton,Australian Grand Prix,2007,3,NaN,6.8
391,Lewis,Hamilton,Malaysian Grand Prix,2007,2,3.000000,5.8
413,Lewis,Hamilton,Bahrain Grand Prix,2007,2,2.500000,3.2
435,Lewis,Hamilton,Spanish Grand Prix,2007,2,2.333333,2.4
457,Lewis,Hamilton,Monaco Grand Prix,2007,2,2.250000,2.6
478,Lewis,Hamilton,Canadian Grand Prix,2007,1,2.200000,2.6
500,Lewis,Hamilton,United States Grand Prix,2007,1,1.800000,2.8
524,Lewis,Hamilton,French Grand Prix,2007,3,1.600000,2.4
546,Lewis,Hamilton,British Grand Prix,2007,3,1.800000,4.0
574,Lewis,Hamilton,European Grand Prix,2007,9,2.000000,3.4
588,Lewis,Hamilton,Hungarian Grand Prix,2007,1,3.400000,4.4
614,Lewis,Hamilton,Turkish Grand Prix,2007,5,3.400000,3.4
633,Lewis,Hamilton,Italian Grand Prix,2007,2,4.200000,2.8
657,Lewis,Hamilton,Belgian Grand Prix,2007,4,4.000000,3.0
676,Lewis,Hamilton,Japanese Grand Prix,2007,1,4.200000,2.6